apiVersion: v1
kind: Template
objects:

##### ImageStream #####

- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "api-${GIT_BRANCH}"
    labels:
      branch: "${GIT_BRANCH}"

##### BuildConfigs #####

- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "api-${GIT_BRANCH}"
    labels:
      app: "${GIT_BRANCH}"
      component: "api"
      branch: "${GIT_BRANCH}"
  spec:
    source:
      git:
        uri: "${GIT_URL}"
        ref: "${GIT_BRANCH}"
      sourceSecret:
        name: "target-git"
    runPolicy: SerialLatestOnly
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "flaskit-${GIT_BRANCH}:latest"
    output:
      to:
        kind: "ImageStreamTag"
        name: "api-${GIT_BRANCH}:latest"
    postCommit:
      script: "echo 'API UNIT TESTS COMMAND'"

##### DeploymentConfig #####

- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    name: "api-${GIT_BRANCH}"
    labels:
      app: "${GIT_BRANCH}"
      component: "api"
      branch: "${GIT_BRANCH}"
  spec:
    template:
      metadata:
        labels:
          app: "${GIT_BRANCH}"
          component: "api"
          branch: "${GIT_BRANCH}"
      spec:
        containers:
          - name: "api"
            image: ' '
            ports:
              - containerPort: 5000
                protocol: "TCP"
                name: http
            env:
              - name: "SENTINEL_HOST"
                value: "redis-sentinel-${GIT_BRANCH}"
              - name: "REDIS_DB"
                value: "1"
              - name: "SENTINEL_PORT"
                value: "26379"
    replicas: 2
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - "api"
          from:
            kind: ImageStreamTag
            name: "api-${GIT_BRANCH}:latest"

##### Parameters #####

parameters:
- description: The git url
  displayName: Git url
  name: GIT_URL
  required: true
- description: The git branch
  displayName: Git branch
  name: GIT_BRANCH
  required: true