apiVersion: v1
kind: Template
objects:

##### ImageStreams #####

- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "consumer-${CONSUMER_NAME}-${GIT_BRANCH}"
    labels:
      app: "${GIT_BRANCH}"
      component: "consumer"
      branch: "${GIT_BRANCH}"

##### BuildConfigs #####

- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "consumer-${CONSUMER_NAME}-${GIT_BRANCH}"
    labels:
      app: "${GIT_BRANCH}"
      component: "consumer"
      branch: "${GIT_BRANCH}"
  spec:
    source:
      git:
        uri: "${GIT_URL}"
        ref: "${GIT_BRANCH}"
      contextDir: "consumer-${CONSUMER_NAME}"
      sourceSecret:
        name: "target-git"
    runPolicy: SerialLatestOnly
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "python:2.7"
          namespace: "openshift"
    output:
      to:
        kind: "ImageStreamTag"
        name: "consumer-${CONSUMER_NAME}-${GIT_BRANCH}:latest"
    postCommit:
      script: "echo 'CONSUMER ${CONSUMER_NAME} UNIT TESTS COMMAND'"

##### DeploymentConfigs #####

- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    name: "consumer-${CONSUMER_NAME}-${GIT_BRANCH}"
    labels:
      app: "${GIT_BRANCH}"
      component: "consumer"
      branch: "${GIT_BRANCH}"
  spec:
    template:
      metadata:
        labels:
          app: "${GIT_BRANCH}"
          component: "consumer"
          branch: "${GIT_BRANCH}"
      spec:
        containers:
          - name: "consumer-${CONSUMER_NAME}-${GIT_BRANCH}"
            image: ' '
            env:
              - name: "SENTINEL_HOST"
                value: "redis-sentinel-${GIT_BRANCH}"
              - name: "SENTINEL_PORT"
                value: "26379"
              - name: "REDIS_DB"
                value: "1"
    replicas: 2
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - "consumer-${CONSUMER_NAME}-${GIT_BRANCH}"
          from:
            kind: ImageStreamTag
            name: "consumer-${CONSUMER_NAME}-${GIT_BRANCH}:latest"

##### Parameters #####

parameters:
- description: Consumer resource name
  displayName: Consumer name
  name: CONSUMER_NAME
  required: true
- description: The git url
  displayName: Git url
  name: GIT_URL
  required: true
- description: The git branch
  displayName: Git branch
  name: GIT_BRANCH
  required: true